
files:
  inputpath: /Users/Nitya/Desktop/Koushik/Bigdata/bcg_analytics_accidents/src/inputs
  charges: Charges_use.csv
  damages: Damages_use.csv
  endorse: Endorse_use.csv
  person: Primary_Person_use.csv
  restrict: Restrict_use.csv
  units:  Units_use.csv


